on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: use a specific action
        id: foo@v1.1
        uses: supesharisuto/composite-actions/random-number-action@v1.1
        with:
          who-to-greet: 'Supesharisuto '

      - run: echo random-number ${{ steps.foo.outputs.random-number }}
          shell: bash
      -
        # for debug only do not enable
        # https://github.com/marketplace/actions/debugging-with-tmate
        name: Run tmate
          #if: ${{ false }}
        if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3
        with:
          install-dependencies: true

